In [1]:
# save as mt5_aggregate_positions.py
import MetaTrader5 as mt5
import pandas as pd

# ---------- Connect to MetaTrader5 ----------
if not mt5.initialize():
    raise RuntimeError("Failed to initialize MT5 connection")

# ---------- Fetch open positions ----------
positions = mt5.positions_get()
if not positions:
    print("No open positions found.")
    mt5.shutdown()
    exit()

# Convert to DataFrame
df = pd.DataFrame(list(positions), columns=positions[0]._asdict().keys())

In [2]:
df

,ticket,time,time_msc,time_update,time_update_msc,type,magic,identifier,reason,volume,price_open,sl,tp,price_current,swap,profit,symbol,comment,external_id
0,1261057978,1760088864,1760088864750,1760327555,1760327555097,0,0,1261057978,0,0.24,3971.30000,0.0,0.0,4076.86000,-13.28,2533.44,XAUUSD,,
1,1261058153,1760088876,1760088876746,1760327964,1760327964555,0,0,1261058153,0,0.51,49.98900,0.0,0.0,51.45400,0.70,747.15,XAGUSD,,
2,1261062639,1760088980,1760088980326,1760327814,1760327814269,1,0,1261062639,0,0.21,0.57505,0.0,0.0,0.57347,0.19,33.18,NZDUSD,,
3,1261075581,1760089290,1760089290297,1760089290,1760089290297,1,0,1261075581,0,1.00,0.57465,0.0,0.0,0.57347,0.90,118.00,NZDUSD,,
4,1261076776,1760089343,1760089343690,1760328055,1760328055020,1,0,1261076776,0,4.00,61.29000,0.0,0.0,60.06000,-23.30,492.00,XTIUSD,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1264043337,1760357030,1760357030903,1760357030,1760357030903,0,0,1264043337,0,10.00,198.08000,0.0,0.0,197.74000,0.00,-3.40,SOLUSD,,
57,1264043366,1760357032,1760357032360,1760357032,1760357032360,0,0,1264043366,0,10.00,198.06000,0.0,0.0,197.74000,0.00,-3.20,SOLUSD,,
58,1264043396,1760357035,1760357035532,1760357035,1760357035532,0,0,1264043396,0,3.00,198.13000,0.0,0.0,197.74000,0.00,-1.17,SOLUSD,,
59,1264046517,1760357155,1760357155108,1760357155,1760357155108,1,0,1264046517,0,0.10,0.65247,0.0,0.0,0.65222,0.00,2.50,AUDUSD,,
60,1264046937,1760357195,1760357195498,1760357195,1760357195498,1,0,1264046937,0,1.00,59.97000,0.0,0.0,60.06000,0.00,-9.00,XTIUSD,,